export const TYPING_WORDS = [
    // --- Original & Previous Words ---
    "time", "year", "people", "way", "day", "man", "thing", "woman", "life", "child", "world",
    "school", "state", "family", "student", "group", "country", "problem", "hand", "part",
    "place", "case", "week", "company", "system", "program", "question", "work", "government",
    "number", "night", "point", "home", "water", "room", "mother", "area", "money", "story",
    "fact", "month", "lot", "right", "study", "book", "eye", "job", "word", "business",
    "issue", "side", "kind", "head", "house", "service", "friend", "father", "power", "hour",
    "game", "line", "end", "member", "law", "car", "city", "community", "name", "president",
    "team", "minute", "idea", "kid", "body", "information", "back", "parent", "face", "others",
    "level", "office", "door", "health", "person", "art", "war", "history", "party", "result",
    "change", "morning", "reason", "research", "girl", "guy", "food", "moment", "air", "teacher",
    "force", "education", "music", "nature", "plant", "space", "field", "light", "dark", "sound",
    "able", "about", "above", "accept", "across", "action", "activity", "actually", "address", "administration",
    "admit", "adult", "affect", "after", "again", "against", "agency", "agent", "agree", "agreement",
    "ahead", "allow", "almost", "alone", "along", "already", "also", "although", "always", "american",
    "among", "amount", "analysis", "animal", "another", "answer", "anyone", "anything", "appear", "apply",
    "approach", "argue", "around", "arrive", "article", "artist", "assume", "attack", "attention", "attorney",
    "audience", "author", "authority", "available", "avoid", "away", "baby", "ball", "bank", "base",
    "beat", "beautiful", "because", "become", "before", "begin", "behavior", "behind", "believe", "benefit",
    "best", "better", "between", "beyond", "bill", "billion", "bit", "black", "blood", "blue",
    "board", "born", "both", "box", "break", "bring", "brother", "budget", "build", "building",
    "call", "camera", "campaign", "candidate", "capital", "card", "care", "career", "carry", "catch",
    "cause", "cell", "center", "central", "century", "certain", "certainly", "chair", "challenge", "chance",
    "character", "charge", "check", "choice", "choose", "church", "citizen", "civil", "claim", "class",
    "clear", "clearly", "close", "coach", "cold", "collection", "college", "color", "come", "commercial",
    "common", "compare", "computer", "concern", "condition", "conference", "congress", "consider", "consumer", "contain",
    "continue", "control", "cost", "could", "couple", "course", "court", "cover", "create", "crime",
    "cultural", "culture", "current", "customer", "data", "dead", "deal", "death", "debate", "decade",
    "decide", "decision", "deep", "defense", "degree", "democrat", "democratic", "describe", "design", "despite",
    "detail", "determine", "develop", "development", "difference", "different", "difficult", "dinner", "direction", "director",
    "discover", "discuss", "discussion", "disease", "doctor", "down", "draw", "dream", "drive", "drop",
    "drug", "during", "each", "early", "east", "easy", "economy", "edge", "editor", "effect",
    "effort", "eight", "either", "election", "else", "employee", "energy", "enjoy", "enough", "enter",
    "entire", "environment", "environmental", "especially", "establish", "even", "evening", "event", "ever", "every",
    "everybody", "everyone", "everything", "evidence", "exactly", "example", "executive", "exist", "expect", "experience",
    "expert", "explain", "factor", "fail", "fall", "fast", "fear", "federal", "feel", "feeling",
    "fight", "figure", "fill", "film", "final", "finally", "financial", "find", "fine", "finger",
    "finish", "fire", "firm", "first", "fish", "floor", "focus", "follow", "foot", "foreign",
    "forget", "form", "former", "forward", "four", "free", "from", "front", "full", "fund",
    "future", "garden", "general", "generation", "glass", "goal", "good", "great", "green", "ground",
    "group", "grow", "growth", "guess", "hair", "half", "hang", "happen", "happy", "hard",
    "have", "heart", "heat", "heavy", "help", "here", "high", "himself", "hold", "hope",
    "hospital", "hotel", "huge", "human", "hundred", "husband", "identify", "image", "imagine", "impact",
    "important", "improve", "include", "including", "increase", "indeed", "indicate", "individual", "industry", "inside",
    "instead", "institution", "interest", "interesting", "interview", "into", "investment", "involve", "item", "itself",
    "join", "just", "keep", "kill", "kitchen", "know", "knowledge", "land", "language", "large",
    "last", "late", "later", "laugh", "lead", "leader", "learn", "least", "leave", "left",
    "legal", "less", "letter", "lie", "likely", "list", "listen", "little", "live", "local",
    "long", "look", "lose", "loss", "love", "machine", "magazine", "main", "maintain", "major",
    "majority", "make", "manage", "management", "manager", "many", "market", "marriage", "material", "matter",
    "maybe", "mean", "measure", "media", "medical", "meet", "meeting", "memory", "mention", "message",
    "method", "middle", "might", "military", "million", "mind", "mission", "model", "modern", "money",
    "more", "most", "mouth", "move", "movement", "movie", "much", "music", "must", "myself",
    "nation", "national", "natural", "near", "nearly", "necessary", "need", "network", "never", "news",
    "newspaper", "next", "nice", "none", "north", "note", "nothing", "notice", "occur", "often",
    "once", "only", "onto", "open", "operation", "opportunity", "option", "order", "organization", "other",
    "outside", "over", "owner", "page", "pain", "painting", "paper", "participant", "particular", "particularly",
    "partner", "pass", "past", "patient", "pattern", "peace", "perform", "performance", "perhaps", "period",
    "personal", "phone", "physical", "pick", "picture", "piece", "plan", "player", "play", "police",
    "policy", "political", "politics", "poor", "popular", "population", "position", "positive", "possible", "potential",
    "practice", "prepare", "present", "pressure", "pretty", "prevent", "price", "private", "probably", "process",
    "produce", "product", "production", "professional", "professor", "project", "property", "protect", "prove", "provide",
    "public", "pull", "purpose", "push", "quality", "quickly", "quite", "race", "radio", "raise",
    "range", "rate", "rather", "reach", "read", "ready", "real", "reality", "realize", "really",
    "receive", "recent", "recently", "recognize", "record", "reduce", "reflect", "region", "relate", "relationship",
    "religious", "remain", "remember", "remove", "report", "represent", "republican", "require", "resource", "respond",
    "response", "responsibility", "rest", "reveal", "rich", "rise", "risk", "road", "rock", "role",
    "rule", "safe", "same", "save", "scene", "science", "scientist", "score", "screen", "seat",
    "second", "section", "security", "seek", "seem", "sell", "send", "senior", "sense", "series",
    "serious", "serve", "seven", "several", "sexual", "shake", "share", "shoot", "short", "shot",
    "should", "shoulder", "show", "sign", "significant", "similar", "simple", "simply", "since", "sing",
    "single", "sister", "site", "situation", "size", "skill", "skin", "small", "smile", "social",
    "society", "soldier", "some", "somebody", "someone", "something", "sometimes", "song", "soon", "sort",
    "source", "south", "southern", "speak", "special", "specific", "speech", "spend", "sport", "spring",
    "staff", "stage", "stand", "standard", "star", "start", "statement", "station", "stay", "step",
    "still", "stock", "stop", "store", "strategy", "street", "strong", "structure", "stuff", "style",
    "subject", "success", "successful", "such", "suddenly", "suffer", "suggest", "summer", "support", "sure",
    "surface", "table", "take", "talk", "task", "teach", "technology", "television", "tell", "tend",
    "term", "test", "than", "thank", "that", "their", "them", "themselves", "then", "theory",
    "there", "these", "they", "think", "third", "this", "those", "though", "thought", "thousand",
    "threat", "three", "through", "throughout", "throw", "thus", "today", "together", "tonight", "total",
    "tough", "toward", "town", "track", "trade", "traditional", "training", "travel", "treat", "treatment",
    "tree", "trial", "trip", "trouble", "true", "truth", "turn", "type", "under", "understand",
    "unit", "until", "upon", "usually", "value", "various", "very", "victim", "view", "violence",
    "visit", "voice", "vote", "wait", "walk", "wall", "want", "watch", "weapon", "wear",
    "weight", "well", "west", "western", "what", "whatever", "when", "where", "whether", "which",
    "while", "white", "whole", "whom", "whose", "wide", "wife", "will", "wind", "window",
    "wish", "with", "within", "without", "wonder", "worker", "write", "writer", "wrong", "yard",
    "yeah", "young", "your", "yourself", "zebra", "zone", "zoom", "zero", "zinc",

    // --- NEW WORDS (Bringing total to 1000+) ---
    // Nature & Environment
    "forest", "river", "mountain", "ocean", "valley", "desert", "jungle", "island", "canyon", "meadow",
    "glacier", "volcano", "cliff", "cave", "swamp", "beach", "coast", "shore", "reef", "wave",
    "tide", "stream", "pond", "lake", "waterfall", "storm", "hurricane", "tornado", "breeze", "cloud",
    "rain", "snow", "fog", "mist", "thunder", "lightning", "weather", "climate", "season", "autumn",
    "winter", "spring", "summer", "sunrise", "sunset", "twilight", "moon", "star", "galaxy", "universe",
    "planet", "asteroid", "comet", "orbit", "gravity", "earth", "soil", "rock", "stone", "sand",
    "dust", "dirt", "mud", "grass", "tree", "leaf", "root", "branch", "flower", "petal",
    "seed", "pollen", "garden", "park", "wildlife", "habitat", "ecosystem", "ecology", "solar", "lunar",

    // Animals & Creatures
    "tiger", "lion", "bear", "wolf", "eagle", "hawk", "shark", "whale", "dolphin", "penguin",
    "giraffe", "elephant", "monkey", "gorilla", "panda", "koala", "kangaroo", "zebra", "rhino", "hippo",
    "camel", "horse", "cow", "pig", "sheep", "goat", "chicken", "duck", "goose", "turkey",
    "rabbit", "mouse", "rat", "squirrel", "fox", "deer", "moose", "buffalo", "bat", "owl",
    "crow", "raven", "pigeon", "parrot", "swan", "frog", "toad", "snake", "lizard", "turtle",
    "spider", "ant", "bee", "wasp", "beetle", "butterfly", "moth", "worm", "snail", "crab",
    "lobster", "shrimp", "squid", "octopus", "jellyfish", "starfish", "seal", "walrus", "otter", "beaver",

    // Home & Daily Life
    "kitchen", "bedroom", "bathroom", "garage", "basement", "attic", "roof", "floor", "ceiling", "stairs",
    "hallway", "corridor", "balcony", "terrace", "porch", "patio", "fence", "gate", "yard", "lawn",
    "furniture", "sofa", "couch", "chair", "table", "desk", "bed", "mattress", "pillow", "blanket",
    "sheet", "towel", "curtain", "carpet", "rug", "lamp", "mirror", "clock", "vase", "shelf",
    "drawer", "closet", "cabinet", "fridge", "freezer", "stove", "oven", "microwave", "toaster", "blender",
    "plate", "bowl", "cup", "glass", "fork", "spoon", "knife", "napkin", "soap", "shampoo",

    // Technology & Science
    "keyboard", "screen", "monitor", "laptop", "tablet", "router", "wifi", "bluetooth", "server", "cloud",
    "robot", "drone", "laser", "rocket", "satellite", "telescope", "microscope", "laboratory", "experiment", "formula",
    "equation", "atom", "molecule", "electron", "proton", "neutron", "physics", "chemistry", "biology", "math",
    "algebra", "geometry", "calculus", "code", "software", "hardware", "database", "algorithm", "variable", "function",
    "loop", "array", "string", "integer", "boolean", "pixel", "vector", "matrix", "network", "system",

    // Food & Drink
    "apple", "banana", "orange", "grape", "strawberry", "blueberry", "raspberry", "cherry", "peach", "pear",
    "plum", "lemon", "lime", "melon", "pineapple", "coconut", "mango", "papaya", "kiwi", "avocado",
    "tomato", "potato", "carrot", "onion", "garlic", "pepper", "cucumber", "lettuce", "spinach", "broccoli",
    "corn", "rice", "wheat", "bread", "pasta", "noodle", "pizza", "burger", "sandwich", "soup",
    "steak", "chicken", "beef", "pork", "fish", "egg", "cheese", "milk", "butter", "yogurt",
    "cream", "sugar", "salt", "spice", "herb", "oil", "vinegar", "sauce", "honey", "jam",
    "coffee", "tea", "juice", "soda", "beer", "wine", "water", "cookie", "cake", "pie",

    // Professions & Roles
    "doctor", "nurse", "surgeon", "dentist", "pilot", "driver", "captain", "sailor", "soldier", "police",
    "detective", "judge", "lawyer", "engineer", "mechanic", "architect", "builder", "plumber", "painter", "artist",
    "writer", "poet", "actor", "singer", "dancer", "musician", "chef", "baker", "waiter", "manager",
    "boss", "leader", "clerk", "guard", "farmer", "fisher", "hunter", "miner", "scientist", "teacher",

    // Emotions & Abstract
    "joy", "sadness", "anger", "fear", "surprise", "disgust", "trust", "envy", "pride", "shame",
    "guilt", "love", "hate", "hope", "despair", "bravery", "cowardice", "wisdom", "folly", "justice",
    "freedom", "liberty", "peace", "war", "truth", "lie", "faith", "belief", "dream", "nightmare",
    "memory", "thought", "idea", "concept", "theory", "reality", "fantasy", "magic", "wonder", "miracle",

    // Verbs (Action)
    "run", "walk", "jump", "fly", "swim", "crawl", "climb", "dive", "dance", "sing",
    "shout", "whisper", "talk", "listen", "watch", "read", "write", "draw", "paint", "cook",
    "eat", "drink", "sleep", "wake", "work", "play", "fight", "laugh", "cry", "smile",
    "frown", "hugs", "kiss", "touch", "hold", "throw", "catch", "push", "pull", "lift",

    // Adjectives (Description)
    "quick", "slow", "fast", "rapid", "swift", "calm", "wild", "tame", "loud", "quiet",
    "silent", "noisy", "sharp", "dull", "bright", "dim", "dark", "light", "heavy", "soft",
    "hard", "rough", "smooth", "wet", "dry", "hot", "cold", "warm", "cool", "clean",
    "dirty", "messy", "neat", "empty", "full", "hollow", "deep", "shallow", "wide", "narrow",
    "tall", "short", "long", "tiny", "huge", "giant", "thick", "thin", "fat", "skinny",

    // Clothing & Accessories
    "shirt", "pants", "shorts", "dress", "skirt", "coat", "jacket", "sweater", "hoodie", "vest",
    "suit", "tie", "scarf", "glove", "mitten", "hat", "cap", "helmet", "belt", "sock",
    "shoe", "boot", "sandal", "sneaker", "slipper", "watch", "ring", "necklace", "earring", "bracelet",
    "glasses", "wallet", "purse", "bag", "backpack", "suitcase", "umbrella", "button", "zipper", "pocket",

    // Transport
    "car", "bus", "train", "tram", "subway", "truck", "van", "taxi", "bike", "bicycle",
    "motorcycle", "scooter", "skateboard", "boat", "ship", "ferry", "yacht", "submarine", "airplane", "jet",
    "helicopter", "glider", "balloon", "rocket", "station", "airport", "harbor", "port", "stop", "ticket",

    // Miscellaneous
    "box", "bag", "bottle", "can", "jar", "lid", "key", "lock", "chain", "rope",
    "string", "wire", "cable", "plug", "switch", "battery", "bulb", "torch", "candle", "match",
    "fire", "smoke", "ash", "dust", "dirt", "mud", "clay", "brick", "concrete", "metal",
    "wood", "glass", "plastic", "paper", "card", "board", "pen", "pencil", "marker", "eraser"
];